name = "adityanawal"
pages_build_output_dir = ".vercel/output/static"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "portfolio-db"
database_id = "3493924d-1d62-4b7c-a479-0552e35314b1"
migrations_dir = "drizzle"
