-- scripts/seed-skills.sql
-- Inject existing static skills from the constants file
INSERT INTO skills (category, name, url) VALUES
('Frontend Development', 'XML', 'https://developer.mozilla.org/en-US/docs/Web/XML/XML_introduction'),
('Frontend Development', 'HTML5', 'https://developer.mozilla.org/en-US/docs/Web/HTML'),
('Frontend Development', 'CSS3', 'https://developer.mozilla.org/en-US/docs/Web/CSS'),
('Frontend Development', 'JavaScript', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript'),
('Frontend Development', 'React.js', 'https://react.dev/'),
('Frontend Development', 'Vite', 'https://vitejs.dev/'),
('Frontend Development', 'Tailwind CSS', 'https://tailwindcss.com/'),
('Frontend Development', 'Bootstrap', 'https://getbootstrap.com/'),
('Backend Development', 'Node.js', 'https://nodejs.org/'),
('Backend Development', 'Express.js', 'https://expressjs.com/'),
('Backend Development', 'Django', 'https://www.djangoproject.com/'),
('Backend Development', 'Flask', 'https://flask.palletsprojects.com/'),
('Backend Development', 'RESTful APIs', 'https://restfulapi.net/'),
('Backend Development', 'JWT Auth', 'https://jwt.io/'),
('Databases', 'MongoDB Atlas', 'https://www.mongodb.com/atlas'),
('Databases', 'MySQL', 'https://www.mysql.com/'),
('Databases', 'Supabase', 'https://supabase.com/'),
('Full-Stack & Web', 'MERN Stack', 'https://www.mongodb.com/mern-stack'),
('Full-Stack & Web', 'Client-Server', 'https://en.wikipedia.org/wiki/Client%E2%80%93server_model'),
('Full-Stack & Web', 'API Integration', 'https://aws.amazon.com/what-is/api-integration/'),
('Cloud & DevOps', 'Vercel', 'https://vercel.com/'),
('Cloud & DevOps', 'Render', 'https://render.com/'),
('Cloud & DevOps', 'GitHub Actions', 'https://github.com/features/actions'),
('Cloud & DevOps', 'Docker', 'https://www.docker.com/'),
('Languages', 'JavaScript', 'https://developer.mozilla.org/en-US/docs/Web/JavaScript'),
('Languages', 'Python', 'https://www.python.org/'),
('Languages', 'Java', 'https://www.java.com/'),
('Languages', 'C/C++', 'https://isocpp.org/'),
('Languages', 'Dart', 'https://dart.dev/'),
('Libraries', 'NumPy', 'https://numpy.org/'),
('Libraries', 'Pandas', 'https://pandas.pydata.org/'),
('Libraries', 'Tkinter', 'https://docs.python.org/3/library/tkinter.html'),
('Libraries', 'Pygame', 'https://www.pygame.org/'),
('Libraries', 'Three.js', 'https://threejs.org/'),
('AI & Dev Tools', 'Generative AI', 'https://cloud.google.com/use-cases/generative-ai'),
('AI & Dev Tools', 'Agentic AI', 'https://www.ibm.com/topics/agentic-ai'),
('AI & Dev Tools', 'Postman', 'https://www.postman.com/'),
('AI & Dev Tools', 'Git & GitHub', 'https://github.com/'),
('AI & Dev Tools', 'Figma', 'https://www.figma.com/'),
('AI & Dev Tools', 'Vercel v0', 'https://v0.dev/');
